apiVersion: v1
kind: Service
metadata:
  name: portfoliod-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: portfoliod
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfoliod-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfoliod-service
                port:
                  number: {{ .Values.service.port }}
